// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToe.Data.DataContext;

namespace TicTacToe.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("TicTacToe.Data.Model.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameResult")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<int>("GameStateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player0")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("PlayerX")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("GameId");

                    b.HasIndex("GameStateId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("TicTacToe.Data.Model.GameState", b =>
                {
                    b.Property<int>("GameStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ML")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameStateId");

                    b.ToTable("GameState");
                });

            modelBuilder.Entity("TicTacToe.Data.Model.Game", b =>
                {
                    b.HasOne("TicTacToe.Data.Model.GameState", "GameState")
                        .WithMany()
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
